stages:
 - build

Ubuntu:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - export BUILD_GENERATOR="Unix Makefiles"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx-sierra

Ubuntu-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DSIMIL_OPTIONALS_AS_REQUIRED=ON -DCLONE_SUBPROJECTS=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS="-DSIMIL_OPTIONALS_AS_REQUIRED=ON -DCLONE_SUBPROJECTS=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Unix Makefiles"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx-sierra
