stages:
 - build

Ubuntu:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - export BUILD_GENERATOR="Unix Makefiles"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx-sierra

Ubuntu-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DSIMIL_OPTIONALS_AS_REQUIRED=ON -DCLONE_SUBPROJECTS=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX-Optional-Deps:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export CMAKE_EXTRA_ARGS="-DSIMIL_OPTIONALS_AS_REQUIRED=ON -DCLONE_SUBPROJECTS=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Unix Makefiles"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx-sierra

Win7:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.56-vs12-x64.bat
  - call %ENVFILESDIR%\HDF5-1.8.14-vs12-x64.bat
  - set CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - set BUILD_GENERATOR=Visual Studio 12 Win64
  - set PATH=%PATH%;"c:\\Program Files\\Git\\bin"
  - bash.exe --login .gitlabci.sh
 tags:
  - win7
