stages:
 - build

Ubuntu:
 stage: build
 script:
  - export CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlabci.sh
 except:
  - master
 tags:
  - ubuntu

Ubuntu-master:
 stage: build
 script:
  - export CMAKE_EXTRA_ARGS="-DCLONE_SUBPROJECTS=ON"
  - export BUILD_GENERATOR="Ninja"
  - export GITHUB_MIRROR_URL="git@github.com:vg-lab/SimIL"
  - bash .gitlabci.sh
 only:
  - master
 tags:
  - ubuntu


OSX:
 stage: build
 script:
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS=-DCLONE_SUBPROJECTS=ON
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx-sierra

Ubuntu-Optional-Deps:
 stage: build
 script:
  - export CMAKE_EXTRA_ARGS="-DSIMIL_OPTIONALS_AS_REQUIRED=ON -DCLONE_SUBPROJECTS=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX-Optional-Deps:
 stage: build
 script:
  - module load Qt-5.9.1
  - export CMAKE_EXTRA_ARGS="-DSIMIL_OPTIONALS_AS_REQUIRED=ON -DCLONE_SUBPROJECTS=ON"
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  - export BUILD_GENERATOR="Ninja"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx-sierra
