stages:
 - build

Ubuntu:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  # - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles"
  - bash .gitlabci.sh
 tags:
  - ubuntu

OSX:
 stage: build
 script:
  - date
  - hostname
  - uname -a
  - export BUILD_OPTIONALS_SUBPROJECTS=1
  # - export CMAKE_EXTRA_TARGETS="test"
  - export BUILD_GENERATOR="Unix Makefiles"
  - export CMAKE_OSX_ARCHITECTURES=x86_64
  - bash .gitlabci.sh
 tags:
  - osx

Win7:
 stage: build
 script:
  - call %ENVFILESDIR%\Boost-1.56-vs12-x64.bat
  - call %ENVFILESDIR%\HDF5-1.8.14-vs12-x64.bat
  # - set CMAKE_EXTRA_TARGETS=RUN_TESTS
  # - set RUN_TESTS=1
  - set BUILD_GENERATOR=Visual Studio 12 Win64
  - set PATH=%PATH%;"c:\\Program Files (x86)\\Git\\bin"
  - bash.exe --login .gitlabci.sh
 tags:
  - win7
